# -*- coding: utf-8 -*-
"""appsolarbr1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oJzKDi7oakflTfnUDf9Sphl7eXqfjHwM
"""

import streamlit as st
import geocoder
import requests
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from io import BytesIO
from PIL import Image
import rasterio
from rasterio.io import MemoryFile
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import matplotlib.pyplot as plt
import math

# BING_KEY = st.secrets.BING_KEY
GOOGLE_SOLAR_KEY = st.secrets.GOOGLE_SOLAR_KEY
SOLAR_INSIGHTS_ENDPOINT = 'https://solar.googleapis.com/v1/buildingInsights:findClosest?location.latitude={}&location.longitude={}&requiredQuality=LOW&key={}'

# streamlit_app.py

import streamlit as st

def check_password():
    """Retorna `True` se o usuário inserir a senha correta."""

    def password_entered():
        """Verifica se a senha inserida pelo usuário está correta."""
        if st.session_state["password"] == st.secrets["password"]:
            st.session_state["password_correct"] = True
            del st.session_state["password"]  # não armazene a senha
        else:
            st.session_state["password_correct"] = False

    if "password_correct" not in st.session_state:
        # Primeira execução, exibir entrada para a senha.
        st.text_input(
            "Senha", type="password", on_change=password_entered, key="password"
        )
        return False
    elif not st.session_state["password_correct"]:
        # Senha incorreta, exibir entrada + erro.
        st.text_input(
            "Senha", type="password", on_change=password_entered, key="password"
        )
        st.error("😕 Senha incorreta")
        return False
    else:
        # Senha correta.
        return True

@st.cache_data
def get_lat_lng_bing(address):
    g = geocoder.bing(address, key=BING_KEY)
    results = g.json
    return (results['lat'], results['lng'])

def get_lat_lng(address):
    """
    Obtém a latitude e longitude de um endereço usando a API de Geocodificação do Google.

    Parâmetros:
    - address: O endereço a ser geocodificado.
    - api_key: Sua chave da API do Google.

    Retorna:
    - Uma tupla contendo a latitude e a longitude.
    """
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={GOOGLE_SOLAR_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        if data['status'] == 'OK':
            latitude = data['results'][0]['geometry']['location']['lat']
            longitude = data['results'][0]['geometry']['location']['lng']
            return latitude, longitude
        else:
            print(f"Erro: {data['status']}")
            return None, None
    else:
        print(f"Falha ao obter os dados: {response.status_code}")
        return None, None

@st.cache_data
def get_solar_insights(lat, lng):
    response = requests.get(SOLAR_INSIGHTS_ENDPOINT.format(lat, lng, GOOGLE_SOLAR_KEY))
    return response.json()

@st.cache_data
def get_google_maps_image(lat, lon, zoom=19, size="600x600", maptype="satélite", api_key=GOOGLE_SOLAR_KEY):
    base_url = "https://maps.googleapis.com/maps/api/staticmap?"
    params = {
        "center": f"{lat},{lon}",
        "zoom": zoom,
        "size": size,
        "maptype": maptype,
        "key": api_key
    }
    response = requests.get(base_url, params=params)
    response.raise_for_status()
    image = Image.open(BytesIO(response.content))
    return image

# Função para exibir uma banda específica de um arquivo GeoTIFF a partir de uma URL com anotação
def display_monthly_flux(data_layers, api_key):
    # Para o fluxo mensal, você precisa lidar com várias bandas, pois ele contém dados para cada mês
    monthly_flux_url_with_key = f"{data_layers['monthlyFluxUrl']}&key={api_key}"
    response = requests.get(monthly_flux_url_with_key)
    if response.status_code == 200:
        with MemoryFile(response.content) as memfile:
            with memfile.open() as dataset:
                for i in range(1, dataset.count + 1):  # Percorrer cada banda
                    fig, ax = plt.subplots()  # Criar uma nova figura e eixos do matplotlib
                    band = dataset.read(i)
                    im = ax.imshow(band) #cmap='viridis')  # Armazenar o objeto mapeável em im
                    #plt.colorbar(im, ax=ax)  # Passar o objeto mapeável para o colorbar
                    ax.set_title(f"Fluxo Solar Mensal - Mês {i}")
                    st.pyplot(fig)  # Passar a figura do matplotlib para st.pyplot()
                    plt.close(fig)  # Fechar a figura
    else:
        print(f"Falha ao buscar os dados. Código de status: {response.status_code}")
        # Função para exibir todas as bandas de um arquivo GeoTIFF a partir de uma URL com anotação
def display_all_geotiff_bands(url, api_key, title):
    url_with_key = f"{url}&key={api_key}"
    response = requests.get(url_with_key)
    if response.status_code == 200:
        with MemoryFile(response.content) as memfile:
            with memfile.open() as dataset:
                fig, ax = plt.subplots()  # Criar uma nova figura e eixos do matplotlib
                if dataset.count > 1:
                    band = dataset.read([1, 2, 3])
                    band = np.transpose(band, (1, 2, 0))
                else:
                    band = dataset.read(1)
                    band = band.squeeze()

                im = ax.imshow(band)  # Armazenar o objeto mapeável em im, cmap='viridis' se dataset.count == 1 else None
                #plt.colorbar(im, ax=ax)  # Passar o objeto mapeável para o colorbar
                ax.set_title(title)
                st.pyplot(fig)  # Passar a figura do matplotlib para st.pyplot()
                plt.close(fig)  # Fechar a figura

# Função para obter camadas de dados
@st.cache_data
def get_data_layers(lat, lon, radius=50, view="FULL_LAYERS", quality="LOW", pixel_size=0.5):
    url = f"https://solar.googleapis.com/v1/dataLayers:get"
    params = {
        "location.latitude": lat,
        "location.longitude": lon,
        "radiusMeters": radius,
        "view": view,
        "requiredQuality": quality,
        "pixelSizeMeters": pixel_size,
        "key": GOOGLE_SOLAR_KEY  # Substitua pela sua chave real da API Solar do Google
    }
    response = requests.get(url, params=params)
    return response.json()

# Visualização 2D
def plot_roof_segments(roof_segments):
    # Criar figura e eixos
    fig, ax = plt.subplots()

    # Plotar cada segmento
    for segment in roof_segments:
        sw = segment['boundingBox']['sw']
        ne = segment['boundingBox']['ne']
        center = segment['center']

        # Calcular a largura e a altura do retângulo
        width = ne['longitude'] - sw['longitude']
        height = ne['latitude'] - sw['latitude']

        # Criar um retângulo representando o segmento do telhado
        rect = patches.Rectangle((sw['longitude'], sw['latitude']), width, height,
                                 linewidth=1, edgecolor='r', facecolor='none')
        ax.add_patch(rect)

        # Usar azimute para representar a orientação do segmento do telhado
        azimuth = segment['azimuthDegrees']
        pitch = segment['pitchDegrees']

        # Calcular o ponto final para a linha que indica a orientação
        # Aqui, estamos usando um método simples para calcular o ponto final; você pode precisar ajustar isso
        end_lon = center['longitude'] + np.cos(np.radians(azimuth)) * width * 0.5
        end_lat = center['latitude'] + np.sin(np.radians(azimuth)) * height * 0.5

        # Desenhar uma linha que indica a orientação do segmento do telhado
        ax.plot([center['longitude'], end_lon], [center['latitude'], end_lat], 'k-')

        # Opcionalmente, anotar o pitch do segmento do telhado
        ax.text(center['longitude'], center['latitude'], f"{pitch:.1f}°",
                fontsize=9, ha='center', va='center')

    # Definir rótulos e título
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    ax.set_title('Segmentos do Telhado com Orientação e Inclinação')

    # Ajustar limites do gráfico
    ax.set_xlim(min([seg['boundingBox']['sw']['longitude'] for seg in roof_segments]),
                max([seg['boundingBox']['ne']['longitude'] for seg in roof_segments]))
    ax.set_ylim(min([seg['boundingBox']['sw']['latitude'] for seg in roof_segments]),
                max([seg['boundingBox']['ne']['latitude'] for seg in roof_segments]))

    # Mostrar o gráfico
    st.pyplot(fig)

# Visualização 3D
def plot_3d_roof_segments(roof_segments):
    if not roof_segments:
        st.write("Nenhum dado de segmentos de telhado disponível.")
        return

    fig, ax = plt.subplots(subplot_kw={'projection': '3d'})

    for segment in roof_segments:
        sw = segment['boundingBox']['sw']
        ne = segment['boundingBox']['ne']
        height = segment['planeHeightAtCenterMeters']
        pitch = math.radians(segment['pitchDegrees'])
        azimuth = math.radians(segment['azimuthDegrees'])

        # Depuração: Imprimir inclinação e azimute
        #st.write(f"Inclinação: {pitch} radianos, Azimute: {azimuth} radianos")

        # Calcular a diferença de altura com base na inclinação e no azimute
        delta_height = np.tan(pitch) * np.sqrt((ne['longitude'] - sw['longitude'])**2 + (ne['latitude'] - sw['latitude'])**2)
        delta_x = delta_height * np.sin(azimuth)
        delta_y = delta_height * np.cos(azimuth)

        vertices = np.array([[sw['longitude'], sw['latitude'], height],
                             [ne['longitude'], sw['latitude'], height + delta_x],
                             [ne['longitude'], ne['latitude'], height + np.sqrt(delta_x**2 + delta_y**2)],
                             [sw['longitude'], ne['latitude'], height + delta_y]])

        # Depuração: Imprimir vértices
        #st.write(vertices)

        # Criar faces
        faces = [[vertices[j] for j in [0, 1, 2, 3]]]

        poly = Poly3DCollection(faces, alpha=0.5, edgecolors='k', linewidths=1)
        ax.add_collection3d(poly)

    # Definir limites dos eixos e rótulos
    ax.set_xlim(min(segment['boundingBox']['sw']['longitude'] for segment in roof_segments),
                max(segment['boundingBox']['ne']['longitude'] for segment in roof_segments))
    ax.set_ylim(min(segment['boundingBox']['sw']['latitude'] for segment in roof_segments),
                max(segment['boundingBox']['ne']['latitude'] for segment in roof_segments))
    ax.set_zlim(0, max(segment['planeHeightAtCenterMeters'] for segment in roof_segments) + 20)  # Limites z ajustados

    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    ax.set_zlabel('Altura')
    ax.set_title('Visualização 3D de Segmentos de Telhado')

    # Mostrar gráfico no Streamlit
    st.pyplot(fig)

# Calculadora
def get_yearly_energy(data, panels_count):
    for config in data['solarPotential']['solarPanelConfigs']:
        if config['panelsCount'] == panels_count:
            return config['yearlyEnergyDcKwh']
    return None

def solar_calculator(data):
    st.subheader('Calculadora de Economia Solar')

    # Extrair número mínimo e máximo de painéis dos resultados da API
    min_panels = data['solarPotential']['solarPanelConfigs'][0]['panelsCount']
    max_panels = data['solarPotential']['maxArrayPanelsCount']

    # Entradas com valores padrão
    # if 'num_panels' not in st.session_state:
    #     st.session_state.num_panels = max_panels

    if 'kw_per_panel' not in st.session_state:
        st.session_state.kw_per_panel = 0.3

    if 'electricity_price' not in st.session_state:
        st.session_state.electricity_price = 0.12

    if 'panel_area_m2' not in st.session_state:
        st.session_state.panel_area_m2 = 1.5

    # st.session_state.num_panels = st.number_input('Número de Painéis Solares', value=st.session_state.num_panels)
    # st.session_state.kw_per_panel = st.number_input('kW por Painel Solar', value=st.session_state.kw_per_panel)
    # st.session_state.electricity_price = st.number_input('Preço da Eletricidade (por kWh)', value=st.session_state.electricity_price)
    # st.session_state.panel_area_m2 = st.number_input('Área por Painel Solar (em m^2)', value=st.session_state.panel_area_m2)

    # Cálculos
    # Entradas
    panels = st.slider('Número de Painéis Solares', min_value=min_panels, max_value=max_panels, value=max_panels)
    user_wattage = st.number_input('Potência do Painel Solar', value=430.0, step=10.0)  # O usuário pode ajustar a potência
    electricity_price = st.number_input('Preço da Eletricidade (R$/kWh)', value=0.81, step=0.01)

    # Calcular
    energia_api = get_yearly_energy(data, panels)
    energia_ajustada = energia_api * (user_wattage / 250.0)  # Ajustar com base na potência especificada pelo usuário
    economia_anual = energia_ajustada * electricity_price

    # Exibir
    st.write(f"Geração Anual de Energia Estimada: {energia_ajustada:.2f} kWh")
    st.write(f"Economia Anual Estimada: €{economia_anual:.2f}")

def main():
    st.title('Insights de Painéis Solares')

    address = st.text_input("Digite seu endereço:")

    # Verifique se o endereço está na session_state
    if 'address' not in st.session_state:
        st.session_state.address = ''

    # Verifique se os dados já estão na session_state e se o endereço foi alterado
    if 'data' not in st.session_state or st.session_state.address != address:
        if st.button('Obter Insights'):
            lat, lng = get_lat_lng(address)
            data = get_solar_insights(lat, lng)
            print(data)
            st.session_state.data = data
            st.session_state.address = address

    # Se os dados estiverem na session_state, exiba-os
    if 'data' in st.session_state:
        data = st.session_state.data
        lat, lng = get_lat_lng(st.session_state.address)

        # Exibir a imagem da casa
        imagem = get_google_maps_image(lat, lng)
        if 'imageryDate' in data:
            st.image(imagem, caption=f"Imagem da Casa de {data['imageryDate']['year']}-{data['imageryDate']['month']}-{data['imageryDate']['day']}", use_column_width=True)
        else:
            st.image(imagem, caption="Imagem da Casa", use_column_width=True)

        # Exibir dados solares
        st.subheader('Potencial Solar')
        # Adicione uma observação usando st.markdown
        st.markdown("_Aviso: Com base nos dados da API Solar do Google (altura do painel - 1,65m, largura do painel - 0,99m, 250 Watts)._")
        st.markdown(f"_Coordenadas do endereço: {lat} {lng}_")
        st.write(f"Número Máximo de Painéis na Matriz: {data['solarPotential']['maxArrayPanelsCount']}")
        st.write(f"Área Máxima de Painéis Solares (m^2): {data['solarPotential']['maxArrayAreaMeters2']}")
        st.write(f"Área Total do Telhado (m^2): {data['solarPotential']['wholeRoofStats']['areaMeters2']}")
        st.write(f"Segmentos de Telhado: {len(data['solarPotential']['roofSegmentStats'])}")
        st.write(f"Máximo de Horas de Sol Anuais: {data['solarPotential']['maxSunshineHoursPerYear']}")

        if 'roofSegmentStats' in data['solarPotential']:
            st.subheader('Visualização 2D de Segmentos de Telhado')
            plot_roof_segments(data['solarPotential']['roofSegmentStats'])

            st.subheader('Visualização 3D de Segmentos de Telhado')
            segmentos_telhado = data['solarPotential']['roofSegmentStats']
            plot_3d_roof_segments(segmentos_telhado)

        # Calculadora
        solar_calculator(data)

        # Expansor com JSON completo
        with st.expander("Clique para expandir a resposta completa da API solar", expanded=False):
            st.write(data)

        if st.button('Obter Camadas de Dados'):
            # Obtenha as camadas de dados
            camadas_dados = get_data_layers(lat, lng)  # Certifique-se de implementar esta função para chamar a segunda API e obter as camadas de dados

            # Exibir os arquivos GeoTIFF do DSM, RGB e da Máscara
            st.subheader('Modelo Digital de Superfície')
            exibir_todas_as_faixas_geotiff(data_layers['dsmUrl'], GOOGLE_SOLAR_KEY, 'Modelo Digital de Superfície')

            st.subheader('Camada Composta RGB')
            exibir_todas_as_faixas_geotiff(data_layers['rgbUrl'], GOOGLE_SOLAR_KEY, 'Camada Composta RGB')

            st.subheader('Máscara de Edifícios')
            exibir_todas_as_faixas_geotiff(data_layers['maskUrl'], GOOGLE_SOLAR_KEY, 'Máscara de Edifícios')

            # Exibir o arquivo GeoTIFF do Fluxo Anual
            st.subheader('Fluxo Anual')
            exibir_todas_as_faixas_geotiff(data_layers['annualFluxUrl'], GOOGLE_SOLAR_KEY, 'Fluxo Anual')

            # Exibir os arquivos GeoTIFF do Fluxo Mensal
            st.subheader('Fluxo Mensal')
            exibir_fluxo_mensal(data_layers, GOOGLE_SOLAR_KEY)

            com st.expander("Clique para expandir a resposta completa da camada de dados", expandido=False):
                st.write(data_layers)

if __name__ == '__main__':
    if check_password():
        main()

